canal.client.instances.example.clusterEnabled: true
canal.client.instances.example.host: 172.16.112.101
canal.client.instances.example.port: 11111
canal.client.instances.example.batchSize: 1000
canal.client.instances.example.acquireInterval: 1000
canal.client.instances.example.retryCount: 3
canal.client.instances.example.servers: hadoop01:9092,hadoop02:9092,hadoop03:9092
canal.client.instances.example.topic: canal
canal.client.instances.example.partition: 0
canal.client.instances.example.kafkaEnable: true
canal.client.instances.example.groupId: test-consumer-group
spring.main.allow-bean-definition-overriding: true
